# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/
services:
  app:
    build:
      context: .
    env_file:
      - .env
  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    env_file:
      - .env

volumes:
  redis_data:

