services:
  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory-policy noeviction
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  redis-data:
