services:
  app:
    build: 
      context: .
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - default

  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory-policy noeviction
    volumes:
      - ./redis-data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - default

volumes:
  redis-data:

networks:
  default:
